# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := city_project glfw glew stb_image glm

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

city_project: glfw glew stb_image glm
	@echo "==== Building city_project ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f city_project.make

glfw: 
	@echo "==== Building glfw ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f glfw.make

glew: 
	@echo "==== Building glew ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f glew.make

stb_image: 
	@echo "==== Building stb_image ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f stb_image.make

glm: 
	@echo "==== Building glm ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f glm.make

clean:
	@${MAKE} --no-print-directory -C . -f city_project.make clean
	@${MAKE} --no-print-directory -C . -f glfw.make clean
	@${MAKE} --no-print-directory -C . -f glew.make clean
	@${MAKE} --no-print-directory -C . -f stb_image.make clean
	@${MAKE} --no-print-directory -C . -f glm.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   city_project"
	@echo "   glfw"
	@echo "   glew"
	@echo "   stb_image"
	@echo "   glm"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
